### ISSUE TITLE
AttributeError: module 'typing' has no attribute '_SpecialForm'

### ISSUE THREAD

**Issue by TriBall3** [real-stanford/flingbot#3]
When I run 
`python run_sim.py --eval --tasks flingbot-normal-rect-eval.hdf5 --load flingbot.pth --num_processes 1 --gui`
there is a problem :

> Traceback (most recent call last):
>   File "run_sim.py", line 1, in <module>
>     from utils import (
>   File "/media/randy/299D817A2D97AD94/fty/flingbot/utils.py", line 2, in <module>
>     from environment import SimEnv, TaskLoader
>   File "/media/randy/299D817A2D97AD94/fty/flingbot/environment/__init__.py", line 1, in <module>
>     from .simEnv import SimEnv
>   File "/media/randy/299D817A2D97AD94/fty/flingbot/environment/simEnv.py", line 3, in <module>
>     from .utils import (
>   File "/media/randy/299D817A2D97AD94/fty/flingbot/environment/utils.py", line 1, in <module>
>     from torch import cat, tensor
>   File "/home/randy/anaconda3/envs/flingbot/lib/python3.6/site-packages/torch/__init__.py", line 643, in <module>
>     from .functional import *  # noqa: F403
>   File "/home/randy/anaconda3/envs/flingbot/lib/python3.6/site-packages/torch/functional.py", line 6, in <module>
>     import torch.nn.functional as F
>   File "/home/randy/anaconda3/envs/flingbot/lib/python3.6/site-packages/torch/nn/__init__.py", line 1, in <module>
>     from .modules import *  # noqa: F403
>   File "/home/randy/anaconda3/envs/flingbot/lib/python3.6/site-packages/torch/nn/modules/__init__.py", line 2, in <module>
>     from .linear import Identity, Linear, Bilinear, LazyLinear
>   File "/home/randy/anaconda3/envs/flingbot/lib/python3.6/site-packages/torch/nn/modules/linear.py", line 6, in <module>
>     from .. import functional as F
>   File "/home/randy/anaconda3/envs/flingbot/lib/python3.6/site-packages/torch/nn/functional.py", line 11, in <module>
>     from .._jit_internal import boolean_dispatch, _overload, BroadcastingList1, BroadcastingList2, BroadcastingList3
>   File "/home/randy/anaconda3/envs/flingbot/lib/python3.6/site-packages/torch/_jit_internal.py", line 34, in <module>
>     from typing_extensions import Final
>   File "/home/randy/anaconda3/envs/flingbot/lib/python3.6/site-packages/typing_extensions.py", line 159, in <module>
>     class _FinalForm(typing._SpecialForm, _root=True):
> AttributeError: module 'typing' has no attribute '_SpecialForm'
> 
How can I solve this problem?

**Comment by RoeweYaoo** [comment]
I met too，would u solve it？？

**Comment by mufenglalala** [comment]
What python version are you using?

**Comment by zcswdt** [comment]
> I met too，would u solve it？？

Hello, have you passed the author's training program?

**Comment by zcswdt** [comment]
> > I met too，would u solve it？？
> 
> Hello, have you passed the author's training program?

Hello, have you passed the author's training program?
