### ISSUE TITLE
ImportError: /home/hc/dextairity/PyFlex/bindings/build/pyflex.cpython-36m-x86_64-linux-gnu.so: undefined symbol: cudaSetupArgument

### ISSUE THREAD

**Issue by canhe173** [real-stanford/flingbot#6]
Hi guys, 
When I run **python test_sim.py**, I get the following error:

`Traceback (most recent call last):
  File "test_sim.py", line 2, in <module>
    from sim_env import SimEnv
  File "/home/hc/dextairity/sim_env.py", line 7, in <module>
    import pyflex
ImportError: /home/hc/dextairity/PyFlex/bindings/build/pyflex.cpython-36m-x86_64-linux-gnu.so: undefined symbol: cudaSetupArgument`

Can anyone help me??

**Comment by ngkhiem97** [comment]
I got the same issue. I'm running the program on Ubuntu 20.04

**Comment by ngkhiem97** [comment]
I'm thinking maybe CUDA is not installed

**Comment by ngkhiem97** [comment]
I have figured out where the error was. I forgot to replace the anaconda3 directory when starting the Nvidia docker container at
```
nvidia-docker run \
	-v $FLINGBOT_PATH:/workspace/flingbot\
	-v /path/to/your/anaconda3:/path/to/your/anaconda3\
	--gpus all --shm-size=64gb  -d -e DISPLAY=$DISPLAY -e QT_X11_NO_MITSHM=1 -it flingbot
```

**Comment by adamhkan** [comment]
I am also having this issue.

**Comment by adamhkan** [comment]
@canhe173 Running the docker container attached instead of detached (removed the `-d` tag in the docker run command) worked for me. Make sure to stay in the flingbot conda environment by using `conda activate flingbot` again after starting the docker container. Then exit the docker container using `exit` before evaluating or training.

**Comment by zcswdt** [comment]
> @canhe173 Running the docker container attached instead of detached (removed the `-d` tag in the docker run command) worked for me. Make sure to stay in the flingbot conda environment by using `conda activate flingbot` again after starting the docker container. Then exit the docker container using `exit` before evaluating or training.

Have you run through the author's training code yet
